import { randomUUID } from 'node:crypto';
import type { SandboxState } from '@toastmasters/contracts';

/**
 * One hand-authored, plausible club — used to seed a fresh in-memory
 * SandboxState the first time a given sandbox person touches the API (see
 * SandboxService). Not reference data, not persisted anywhere; a new call
 * to this function is a clean slate.
 */
export function createSandboxFixture(): SandboxState {
  const members: SandboxState['members'] = [
    {
      id: randomUUID(),
      fullName: 'Amara Chen',
      role: 'President',
      email: 'amara.chen@example.com',
      joinedAt: '2023-09-12',
      pathway: 'Dynamic Leadership',
      pathwayLevel: 5,
    },
    {
      id: randomUUID(),
      fullName: 'Priya Nair',
      role: 'VP Education',
      email: 'priya.nair@example.com',
      joinedAt: '2022-03-04',
      pathway: 'Motivational Strategies',
      pathwayLevel: 4,
    },
    {
      id: randomUUID(),
      fullName: 'Diego Alvarez',
      role: 'VP Membership',
      email: 'diego.alvarez@example.com',
      joinedAt: '2023-01-20',
      pathway: 'Engaging Humor',
      pathwayLevel: 3,
    },
    {
      id: randomUUID(),
      fullName: 'Fatima Rahman',
      role: 'VP Public Relations',
      email: 'fatima.rahman@example.com',
      joinedAt: '2024-02-10',
      pathway: 'Presentation Mastery',
      pathwayLevel: 2,
    },
    {
      id: randomUUID(),
      fullName: 'Kenji Watanabe',
      role: 'Secretary',
      email: 'kenji.watanabe@example.com',
      joinedAt: '2024-06-01',
      pathway: 'Persuasive Influence',
      pathwayLevel: 2,
    },
    {
      id: randomUUID(),
      fullName: 'Grace Mensah',
      role: 'Treasurer',
      email: 'grace.mensah@example.com',
      joinedAt: '2023-11-15',
      pathway: 'Dynamic Leadership',
      pathwayLevel: 3,
    },
    {
      id: randomUUID(),
      fullName: 'Omar Haddad',
      role: 'Sergeant at Arms',
      email: 'omar.haddad@example.com',
      joinedAt: '2024-08-19',
      pathway: 'Presentation Mastery',
      pathwayLevel: 1,
    },
    {
      id: randomUUID(),
      fullName: 'Lucia Ferreira',
      role: 'Member',
      email: 'lucia.ferreira@example.com',
      joinedAt: '2025-01-08',
      pathway: 'Engaging Humor',
      pathwayLevel: 1,
    },
    {
      id: randomUUID(),
      fullName: 'Noah Whitfield',
      role: 'Member',
      email: 'noah.whitfield@example.com',
      joinedAt: '2025-04-22',
      pathway: 'Motivational Strategies',
      pathwayLevel: 1,
    },
    {
      id: randomUUID(),
      fullName: 'Yuki Tanaka',
      role: 'Member',
      email: 'yuki.tanaka@example.com',
      joinedAt: '2025-06-30',
      pathway: 'Dynamic Leadership',
      pathwayLevel: 1,
    },
  ];

  return {
    members,
    meetings: [
      {
        id: randomUUID(),
        theme: 'Storytelling Under Pressure',
        scheduledAt: '2026-07-10T18:00:00.000Z',
        status: 'completed',
        agenda: [
          {
            id: randomUUID(),
            order: 1,
            title: 'Word of the Day',
            speaker: 'Kenji Watanabe',
            durationMinutes: 3,
          },
          {
            id: randomUUID(),
            order: 2,
            title: 'Table Topics',
            speaker: 'Diego Alvarez',
            durationMinutes: 15,
          },
          {
            id: randomUUID(),
            order: 3,
            title: 'Prepared Speech: Finding Your Voice',
            speaker: 'Lucia Ferreira',
            durationMinutes: 7,
          },
          {
            id: randomUUID(),
            order: 4,
            title: 'Prepared Speech: The Long Way Home',
            speaker: 'Omar Haddad',
            durationMinutes: 6,
          },
          {
            id: randomUUID(),
            order: 5,
            title: 'Evaluations',
            speaker: 'Priya Nair',
            durationMinutes: 12,
          },
        ],
      },
      {
        id: randomUUID(),
        theme: 'Leading Without a Title',
        scheduledAt: '2026-07-17T18:00:00.000Z',
        status: 'completed',
        agenda: [
          {
            id: randomUUID(),
            order: 1,
            title: 'Word of the Day',
            speaker: 'Grace Mensah',
            durationMinutes: 3,
          },
          {
            id: randomUUID(),
            order: 2,
            title: 'Table Topics',
            speaker: 'Fatima Rahman',
            durationMinutes: 15,
          },
          {
            id: randomUUID(),
            order: 3,
            title: 'Prepared Speech: The First Yes',
            speaker: 'Noah Whitfield',
            durationMinutes: 6,
          },
          {
            id: randomUUID(),
            order: 4,
            title: 'Evaluations',
            speaker: 'Amara Chen',
            durationMinutes: 10,
          },
        ],
      },
      {
        id: randomUUID(),
        theme: 'Yes, And: Improvisation in Speaking',
        scheduledAt: '2026-07-24T18:00:00.000Z',
        status: 'completed',
        agenda: [
          {
            id: randomUUID(),
            order: 1,
            title: 'Word of the Day',
            speaker: 'Yuki Tanaka',
            durationMinutes: 3,
          },
          {
            id: randomUUID(),
            order: 2,
            title: 'Table Topics',
            speaker: 'Kenji Watanabe',
            durationMinutes: 15,
          },
          {
            id: randomUUID(),
            order: 3,
            title: 'Prepared Speech: Improv for Introverts',
            speaker: 'Diego Alvarez',
            durationMinutes: 7,
          },
          {
            id: randomUUID(),
            order: 4,
            title: 'Evaluations',
            speaker: 'Priya Nair',
            durationMinutes: 10,
          },
        ],
      },
      {
        id: randomUUID(),
        theme: 'The Art of the Ask',
        scheduledAt: '2026-08-07T18:00:00.000Z',
        status: 'upcoming',
        agenda: [
          {
            id: randomUUID(),
            order: 1,
            title: 'Word of the Day',
            speaker: null,
            durationMinutes: 3,
          },
          { id: randomUUID(), order: 2, title: 'Table Topics', speaker: null, durationMinutes: 15 },
          {
            id: randomUUID(),
            order: 3,
            title: 'Prepared Speech: Negotiating with Confidence',
            speaker: 'Fatima Rahman',
            durationMinutes: 7,
          },
        ],
      },
      {
        id: randomUUID(),
        theme: 'Club Officer Elections Night',
        scheduledAt: '2026-08-14T18:00:00.000Z',
        status: 'upcoming',
        agenda: [
          {
            id: randomUUID(),
            order: 1,
            title: 'Word of the Day',
            speaker: null,
            durationMinutes: 3,
          },
          {
            id: randomUUID(),
            order: 2,
            title: 'Officer Nominations',
            speaker: 'Amara Chen',
            durationMinutes: 20,
          },
          {
            id: randomUUID(),
            order: 3,
            title: 'Elections',
            speaker: 'Amara Chen',
            durationMinutes: 15,
          },
        ],
      },
    ],
    planner: [
      {
        id: randomUUID(),
        meetingDate: '2026-08-07',
        theme: 'The Art of the Ask',
        toastmaster: 'Grace Mensah',
        generalEvaluator: 'Priya Nair',
      },
      {
        id: randomUUID(),
        meetingDate: '2026-08-14',
        theme: 'Club Officer Elections Night',
        toastmaster: 'Amara Chen',
        generalEvaluator: null,
      },
      {
        id: randomUUID(),
        meetingDate: '2026-08-21',
        theme: 'Humor in the Workplace',
        toastmaster: null,
        generalEvaluator: null,
      },
      {
        id: randomUUID(),
        meetingDate: '2026-08-28',
        theme: 'Speaking Without Slides',
        toastmaster: 'Diego Alvarez',
        generalEvaluator: null,
      },
      {
        id: randomUUID(),
        meetingDate: '2026-09-04',
        theme: 'International Speech Contest Prep',
        toastmaster: null,
        generalEvaluator: null,
      },
    ],
    guests: [
      {
        id: randomUUID(),
        fullName: 'Harper Douglas',
        email: 'harper.douglas@example.com',
        invitedBy: 'Diego Alvarez',
        pipelineStatus: 'converted',
        visitedAt: '2026-06-12',
      },
      {
        id: randomUUID(),
        fullName: 'Ines Moreau',
        email: 'ines.moreau@example.com',
        invitedBy: 'Fatima Rahman',
        pipelineStatus: 'visited',
        visitedAt: '2026-07-10',
      },
      {
        id: randomUUID(),
        fullName: 'Tobias Klein',
        email: 'tobias.klein@example.com',
        invitedBy: 'Amara Chen',
        pipelineStatus: 'invited',
        visitedAt: null,
      },
      {
        id: randomUUID(),
        fullName: 'Zanele Dube',
        email: 'zanele.dube@example.com',
        invitedBy: null,
        pipelineStatus: 'new',
        visitedAt: null,
      },
      {
        id: randomUUID(),
        fullName: 'Marcus Reyes',
        email: null,
        invitedBy: 'Grace Mensah',
        pipelineStatus: 'new',
        visitedAt: null,
      },
    ],
    education: [
      {
        memberId: idOf(members, 'Amara Chen'),
        memberName: 'Amara Chen',
        pathway: 'Dynamic Leadership',
        level: 5,
        projectsCompleted: 9,
        projectsTotal: 10,
      },
      {
        memberId: idOf(members, 'Priya Nair'),
        memberName: 'Priya Nair',
        pathway: 'Motivational Strategies',
        level: 4,
        projectsCompleted: 6,
        projectsTotal: 9,
      },
      {
        memberId: idOf(members, 'Diego Alvarez'),
        memberName: 'Diego Alvarez',
        pathway: 'Engaging Humor',
        level: 3,
        projectsCompleted: 4,
        projectsTotal: 8,
      },
      {
        memberId: idOf(members, 'Fatima Rahman'),
        memberName: 'Fatima Rahman',
        pathway: 'Presentation Mastery',
        level: 2,
        projectsCompleted: 2,
        projectsTotal: 8,
      },
      {
        memberId: idOf(members, 'Kenji Watanabe'),
        memberName: 'Kenji Watanabe',
        pathway: 'Persuasive Influence',
        level: 2,
        projectsCompleted: 2,
        projectsTotal: 8,
      },
      {
        memberId: idOf(members, 'Grace Mensah'),
        memberName: 'Grace Mensah',
        pathway: 'Dynamic Leadership',
        level: 3,
        projectsCompleted: 5,
        projectsTotal: 10,
      },
    ],
  };
}

function idOf(members: SandboxState['members'], fullName: string): string {
  const member = members.find((m) => m.fullName === fullName);
  if (!member) throw new Error(`Sandbox fixture: no member named "${fullName}"`);
  return member.id;
}
